### ISSUE TITLE
Decoding weak signals - frequency reporting

### ISSUE THREAD

**Issue by KevWal** [projecthorus/horus-gui#18]
Hi

When decoding very weak signals at -7SNR or so, they are impossible to see on the Spectra, and hence I can not tell how accurate my radio tuning is, am I very close to one edge of the audio band or the other...  Against each decoded packet in the Log, or perhaps in the 'Data' box could we add frequency and SNR of the last decoded packet?

Thanks very much
Kevin

**Comment by darksidelemm** [comment]
This is actually surprisingly hard to do.

The modem doesn't give our SNR or frequency estimator data on a per-packet basis. Instead, it's on a block of samples basis, and for the data rates we are using, that sample block ends up being almost a seconds worth of samples.

By the time a packet is emitted from the modem, the frequency estimator data and SNR data are often invalid (if the payload is transmitting intermittently). It's possible to do a 'peak hold' on the SNR, but to be able to gather the frequency data at the right time, the SNR would need to be thresholded - and as you've probably seen, when decoding really weak signals the SNR is barely above the noise floor. 

So, unfortunately, I don't have an easy solution for this one.

**Comment by KevWal** [comment]
Thanks for the response, no problem, replying on others closer to the payload to tell us the frequency it will have to be :)
