### ISSUE TITLE
PyAudio Python 3.10 compatibility Issue

### ISSUE THREAD

**Issue by Dieter9** [projecthorus/horus-gui#22]
On Arch Linux there has been an update of python3 to version 3.10.
Since then the audio input of horus-gui does not work and I get the following error message at runtime:

> 2021-12-15 15:47:37,068 INFO: Started Audio Processing.
> SystemError: PY_SSIZE_T_CLEAN macro must be defined for '#' formats
> Traceback (most recent call last):
>   File "/home/my/horusgui/gui.py", line 931, in processQueues
>     def processQueues():
> SystemError

The UDP input still works.

**Comment by darksidelemm** [comment]
This appears to be an issue in PyAudio:
https://stackoverflow.com/questions/70344884/pyaudio-write-systemerror-py-ssize-t-clean-macro-must-be-defined-for-format

I'm not sure how quickly this is going to be fixed, so unfortunately I think Python 3.10 support may be a while away.

**Comment by darksidelemm** [comment]
Closing this one as it seems pyaudio has been fixed. Has been tested OK on Python 3.11
