### ISSUE TITLE
Timer showing seconds since last received frame

### ISSUE THREAD

**Issue by boonie-oet-gelaen** [projecthorus/horus-gui#29]
Hi,

Please consider adding a timer that will show the number of seconds increasing from 0 after each received frame. This would be useful to quickly see when to expect the next frame. It could be a toggle function when one clicks on the time that it changes to this timer and on the next click that it shows the time again. Thanks and greetings from the Netherlands.

**Comment by darksidelemm** [comment]
Working on this now...

<img width="957" alt="Screen Shot 2023-07-01 at 10 57 46" src="https://github.com/projecthorus/horus-gui/assets/1040275/0d7cad65-feaa-4071-bb07-9021eaeeb422">

**Comment by darksidelemm** [comment]
Added in https://github.com/projecthorus/horus-gui/releases/tag/v0.3.11
