### ISSUE TITLE
Automatic antenna tracking and GPS dropout

### ISSUE THREAD

**Issue by Dieter9** [projecthorus/horus-gui#31]
I have tried a little bit with Horus-Gui, a directional antenna and automatic antenna tracking via rotctl. When the observed sonde had a temporary GPS dropout, I could observe a funny bug. 

The sonde transmitted longitude = 0, latitude=0, after which Horus-Gui turned the antenna exactly in this direction. :-)
So I couldn't receive the sonde at all, even when the sonde was sending correct coordinates again.

I made a small change to the program gui.py to prevent this effect. Please check my improvement if it is possible to apply it to your software.

73 de Dieter, DK6OV

```python
-- gui.py	2023-07-15 08:58:21.747580280 +0200
+++ gui-new.py	2023-07-24 12:57:00.201496270 +0200
@@ -1015,8 +1015,8 @@
                     widgets['latestPacketBearingValue'].setText(f"{_position_info['bearing']:.1f}")
                     widgets['latestPacketElevationValue'].setText(f"{_position_info['elevation']:.1f}")
                     widgets['latestPacketRangeValue'].setText(f"{_position_info['straight_distance']/1000.0:.1f}")
-
-                    if rotator:
+  
+                    if rotator and not ( _decoded['latitude']==0 and _decoded['longitude']==0 ):
                         try:
                             rotator.set_azel(_position_info['bearing'], _position_info['elevation'], check_response=False)
                             widgets["rotatorCurrentPositionValue"].setText(f"{_position_info['bearing']:3.1f}˚,  {_position_info['elevation']:2.1f}˚")
```

**Comment by darksidelemm** [comment]
Ahh that is a good catch! I'll try and get this fixed ASAP and get a new release out.

Just curious, was the sonde in flight when its GPS dropped out?

**Comment by Dieter9** [comment]
@

**Comment by darksidelemm** [comment]
Reopened until I actually fix it :-)

**Comment by darksidelemm** [comment]
Should be fixed in https://github.com/projecthorus/horus-gui/releases/tag/v0.3.13
