### ISSUE TITLE
Installing Horus-GUI PyQt5 error 

### ISSUE THREAD

**Issue by Woeka** [projecthorus/horus-gui#34]
Installing horus-gui dit not work, hardware: Raspberry-PI with Bullseye

$ pip install -r requirements.txt

Gave an error:

Collecting PyQt5
  Using cached PyQt5-5.15.9.tar.gz (3.2 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
  Preparing metadata (pyproject.toml) ... error

My sollution:
sudo apt install qtbase5-dev
pip install pyqt5 --config-settings --confirm-license= --verbose

**Comment by dalewegner** [comment]
Had same pyproject.toml error so tried solution and during pip install -e . got new error pyproject.toml killed..
![pyproject](https://github.com/projecthorus/horus-gui/assets/19360146/19b45076-9006-4497-8e17-711065c4b488)

**Comment by darksidelemm** [comment]
Horus-GUI should now work with the latest pyqtgraph and PyQt5 versions, so no more version pinning required. Please try again and re-open the issue if you're still having problems.
