### ISSUE TITLE
Line between balloon and RX not visible

### ISSUE THREAD

**Issue by hem0773** [projecthorus/horus-gui#35]
Line between balloon and RX not visible
Can somebody tell me why
![grafik](https://github.com/projecthorus/horus-gui/assets/57199067/f83b30be-b1d6-4580-aa78-a0f2629cf27a)

**Comment by darksidelemm** [comment]
The green line is only shown for the most recent packet. The receiver list does shows data up to a few minutes old. 

If we showed green lines for all receivers for more than just the most recent packet, the map would just be a mess of green lines!

**Comment by darksidelemm** [comment]
Your callsign appears to have a space on the end of it. For some reason this is actually breaking the green line function. Try removing that space.
