### ISSUE TITLE
Default callsign

### ISSUE THREAD

**Issue by TheSkorm** [projecthorus/horus-gui#36]
Horus-gui should either ask for a callsign on first startup or throw an error message when starting with `N0CALL`. UI should probably indicate that this field doesn't need to be an amateur radio callsign - just something unique. This is the prevent issues when https://github.com/projecthorus/sondehub-infra/pull/135 is merged

**Comment by darksidelemm** [comment]
Fixed in v0.3.15 - a popup box comes up if the callsign is set to N0CALL and the start button is pressed.
