### ISSUE TITLE
Reported SNR for RTTY does not match uploaded value

### ISSUE THREAD

**Issue by zanco** [projecthorus/horus-gui#38]
![image](https://github.com/projecthorus/horus-gui/assets/4477734/2497d392-d3fd-4c5e-ab18-479853b210ab)

Hi, when receiving RTTY the SNR indicator shows clearly positive SNR, but the value at the end of the string and value uploaded are negative.

Thanks
Ben

**Comment by darksidelemm** [comment]
OK, I probably need to increase the 'lookback' period of the SNR calculation code when in RTTY mode.

For my own notes:
- SNR obtained in get_latest_snr here: https://github.com/projecthorus/horus-gui/blob/master/horusgui/gui.py#L876
- Check the current assumption about status updates is true.
- Work out a suitable length when in RTTY mode (maybe double that for horus binary?)

**Comment by darksidelemm** [comment]
I currently don't have a functioning RTTY payload to test with. If you could get me a recording (with at least 5 or so packets) of a RTTY payload where this issue is occurring that will help me debug things...

**Comment by zanco** [comment]
[Uploading pa0cab-rtty-100bd-7n2.zip…]()
(removed most of the spaces and beeps and the CW identification transmission.)

**Comment by darksidelemm** [comment]
That didn't appear to upload correctly. You can also email me the sample at vk5qi@rfhead.net

**Comment by darksidelemm** [comment]
OK, it looks like the time window for SNR calculations for RTTY will need to be expanded out to maybe 15 seconds to account for the pretty huge RTTY decoding buffer that it used within the demod.

**Comment by darksidelemm** [comment]
There's a test build of v0.3.17 with this fix here: https://github.com/projecthorus/horus-gui/actions/runs/8829173602

**Comment by zanco** [comment]
Let the image do the work :-)

![image](https://github.com/projecthorus/horus-gui/assets/4477734/37d2e992-0640-4416-ae9a-061f11344d22)


Excellent work, now tested at 300 baud 8n2

Thanks !

**Comment by darksidelemm** [comment]
OK, this is released in 0.3.17 :)
