### ISSUE TITLE
horus-gui_v0.3.17 for windows 7-8  ?

### ISSUE THREAD

**Issue by DiX880** [projecthorus/horus-gui#40]
Greetings. Tell me where to get horus-gui_v0.3.17 for windows 8 to install on an old tablet ?

**Comment by darksidelemm** [comment]
Sorry, I can't provide builds for anything older than Windows 10 anymore. This has been the case over almost a year now.

**Comment by DiX880** [comment]
As an exception, there may be any version in the archives win32 . Will you send it to the post office? skynet_1981@mail.ru

**Comment by darksidelemm** [comment]
As I said, I have not supported Windows 7 for almost a year, and the versions from before then are very out of date. I have never supported 32-bit windows either, it's always been 64-bit only.

The best I can point you to is these old build instructions for Windows 7 https://github.com/projecthorus/horus-gui/wiki/Creating-Binary-Packages#setting-up-to-run-horus-gui but I *cannot* provide any further support for this.
